import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import { Header } from "@/core/shared/components";

export const metadata: Metadata = {
  title: "Show what you wish",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="app">
          <AntdRegistry>
            <ConfigProvider
              theme={{
                token: {},
                components: {
                  Menu: {
                    itemBg: "transparrent",
                    colorBorder: "transparrent",
                  },
                },
              }}
            >
              <Header />
              {children}
            </ConfigProvider>
          </AntdRegistry>
        </div>
      </body>
    </html>
  );
}
